from setuptools import setup, find_packages

setup(
    name="safe-audio",
    version="0.1.0",
    description="Simple, Adaptive, Failure-Proof Audio Addition to a VL Model",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0", 
        "torchaudio>=2.0.0",
        "transformers>=4.30.0",
        "datasets>=2.12.0",
        "accelerate>=0.20.0",
        "peft>=0.4.0",
        "scipy>=1.10.0",
        "numpy>=1.24.0",
        "librosa>=0.10.0",
        "soundfile>=0.12.0",
        "pillow>=9.5.0",
        "opencv-python>=4.7.0",
        "scikit-learn>=1.2.0",
        "matplotlib>=3.7.0",
        "wandb>=0.15.0",
        "tensorboard>=2.12.0",
        "tqdm>=4.65.0",
        "einops>=0.6.0",
        "timm>=0.9.0",
        "laion-clap>=1.1.0",
        "openai-whisper>=20230314",
        "evaluate>=0.4.0",
        "pycocotools>=2.0.6",
    ],
)